### ISSUE TITLE
Add an interactive way to search for specific mutations

### ISSUE THREAD

**Issue by WillHannon-MCB** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#117]
@Bernadetadad mentioned in [this issue](https://github.com/dms-vep/dms-vep-pipeline-3/issues/118) that we should have a quick, interactive way to search for the phenotypes associated with specific mutations. This will be handy for people who have a mutation they've identified through surveillance and want to find it's effect on HA stability, Sialic acid usage, etc.. 

I've integrated a version of this into the `VitePress` homepage on a [new branch](https://github.com/dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/tree/interactive-phenotype-tool). Would either @Bernadetadad or @jbloom mind checking if it's what they had in mind?

**Comment by Bernadetadad** [comment]
Nice! this will definitely be very useful. 

A few points:
- we definitely need to specify what numbering scheme is being used (H3)
- the 'Sites' bar only takes mutations, so should probably be named 'Mutations'
- not sure what's the benefit of also showing the full summary table there are opposed to just the table with selected mutations (if we want to keep the full table it should at least be at the bottom of the section not at the top)
- we should name it something else than 'Interactive Phenotype Tool', I think this doesn't convey clearly what it is. Can we just call it something simple like 'Mutation effect lookup tool'
- I wonder if we should have this not at summary tab but maybe even make it it's own tab, because really half of the time I want to just use this tool to look at specific mutation effects as opposed to scroll though various heat maps. Or maybe we should put this at the top of the summary page? @jbloom thoughts?
- I feel like knowing exactly what numbering scheme is used in our summary table and/or in some paper will end up being the most confusing thing here, is there a way we could let people set what numbering scheme they are using (might require joining `phenotypes.csv` with `site_numbering_map.csv`)?

**Comment by jbloom** [comment]
Nice start on this, @WillHannon-MCB. This could be very useful with a few tweaks.

Regarding those tweaks, I largely agree with @Bernadetadad, adding to and re-emphasizing these points:

 - You currently have it set up to enter mutations, not sites. So if that is the case, it should say it is taking mutations, not sites.
 - The page is way too cluttered. I don't get the benefits of the summary of the whole dataset as you would have to scroll through the entire thing to find any mutation.
 - Also, having histograms over things like "site" or "wildtype" make no sense; the distribution of these is not interesting. They should maybe be shown as labels, but no one would care about a histogram of these.
 - For select the phenotype for the histogram at the bottom (which is interesting), can that be a dropdown of the choices, which should obviously only encode phenotypes and not site numbers etc.
 - I agree that "interactive phenotype tool" is not a good name, and like what Bernadeta suggests.
 - I agree with Bernadeta re numbering scheme. At **minimum** it needs to explain which one is being used, and ideally people could choose.
 - It would actually be nice if people could enter just sites as well as mutations to select. Sometimes you just might want to see all mutations at a site.
 - Use a better CSV. This is not really the correct one to be pulling data from as we want to show ferret escape and mouse escape separately, not this "species sera escape" which is just an average.
 - Once these things are cleaned up, I think this could be linked to either the main or the summary page.
 - Can you document this to indicate how it would be configured to draw from a different CSV?

**Comment by WillHannon-MCB** [comment]
Thanks for the suggestions! I'll start addressing these ASAP. The only thing I might not be able to fix is this:

>Also, having histograms over things like "site" or "wildtype" make no sense; the distribution of these is not interesting. They should maybe be shown as labels, but no one would care about a histogram of these.

I'm using `Observable` to make this lookup tool. The interactive table is a tool made by them, and to my knowledge, there isn't a way to selectively hide those histograms. I could do away with all of the histograms? They're probably unnecessary if there's a histogram for the phenotype of interest.

**Comment by Bernadetadad** [comment]
I would do away with all of them, I would never really look at those tiny histograms anyway

**Comment by WillHannon-MCB** [comment]
Agreed!

**Comment by WillHannon-MCB** [comment]
Alright @jbloom and @Bernadetadad, I updated the tool with your suggestions:

- [ ] Specify the numbering scheme.
- [ ] Select either sites or mutations.
- [ ] Remove the full summary table.
- [ ] Remove the unnecessary histograms.
- [ ] Change the name to something more appropriate.
- [ ] Change the phenotype selection to a drop-down menu.
- [ ] Change to a csv with separate mouse and ferret escape values.

The tool is still on the `summary` page, but I'm happy to move it elsewhere. 

This is fairly bespoke, so I'd have to make a new one for a different project. I could build a generalizable version that doesn't rely on Observable. That could also be a self-contained project for an undergraduate intern.

**Comment by jbloom** [comment]
And just to make life easier in looking at this, the link to the tool [is here](https://observablehq.com/embed/@willhannon-mcb/h5n1-dms-phenotype-lookup?cells=viewof+numberingScheme%2Cviewof+sites%2Cviewof+phenotype%2Cplot%2Cfilter_df%22%3E%3C/iframe%3E).

I think this looks good with the following suggestions:
 - I'm not sure how widely used `Reference H1` numbering is. I would personally think we should include sequential numbering in addition or instead of `Reference H1`, as computational biology people use that.
 - It's not essential, but the one other nice feature I could imagine is that when you enter the mutation / site in one numbering scheme, it also shows you what it is in different numbering schemes.

**Comment by Bernadetadad** [comment]
Really nice @WillHannon-MCB ! Could we rename y-axis to something like `number of mutations`, `frequency` got me confused for a second

**Comment by WillHannon-MCB** [comment]
How does [this](https://observablehq.com/embed/@willhannon-mcb/h5n1-dms-phenotype-lookup@251?cells=viewof+numberingScheme%2Cviewof+sites%2CtransposedSitesString%2Cviewof+phenotype%2Cplot%2Cfilter_df) look?

**Comment by Bernadetadad** [comment]
looks great to me

**Comment by jbloom** [comment]
Looks great to me as well.
