### ISSUE TITLE
Inconsistency between the reference sequence and DMS wildtype

### ISSUE THREAD

**Issue by Chonghao98** [dms-vep/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS#122]
Hi,

I found that there are some mismatches between the reference sequence and the DMS wildtype.

Based on the American_Wigeon_H5N1_HA_EPI2709137.fa, I convert it into the amino acid sequence as follow:
MENIVLLLAIVSLVKSDQICIGYHANNSTEQVDTIMEKNVTVTHAQDILEKTHNGKLCDLNGVKPLILKDCSVAGWLLGNPMCDEFIRVPEWSYIVERANPANDLCYPGSLNDYEELKHMLSRINHFEKILIIPKSSWPNHETSLGVSAACPYQGAPSFFRNVVWLIKKNDAYPTIKISYNNTNREDLLILWGIHHSNNAEEQTNLYKNPTTYISVGTSTLNQRLAPKIATRSQVNGQRGRMDFFWTILKPDDAIHFESNGNFIAPEYAYKIVKKGDSTIMKSGVEYGHCNTKCQTPVGAINSSMPFHNIHPLTIGECPKYVKSNKLVLATGLRNSPLREKRRKRGLFGAIAGFIEGGWQGMVDGWYGYHHSNEQGSGYAADKESTQKAIDGVTNKVNSIIDKMNTQFEAVGREFNNLERRIENLNKKMEDGFLDVWTYNAELLVLMENERTLDFHDSNVKNLYDKVRLQLRDNAKELGNGCFEFYHKCDNECMESVRNGTYDYPQYSEEARLKREEISGVKLESVGTYQILSIYSTAASSLALAIMMAGLSLWMCSNGSLQCRICI

In this case, the DMS dataset (phenotypes.csv) does not align with the reference sequence. For example, if I align the site 10 to be 'S', then site 100 should be 'C' rather than 'G'.

Did I made some mistakes during the conversion or there are some typos in the phenotype.csv file?

Thank you.

**Comment by jbloom** [comment]
@Chonghao98, when aligning to the protein sequence, are you looking at the *sequential_site* column of the `phenotypes.csv` rather than the *site* column?

The sites used in the site column are H3 numbering, and then the `phenotypes.csv` shows several other numbering schemes as well.

See [here](https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/numbering.html).

Let us know if this does not answer your question.

**Comment by Chonghao98** [comment]
@jbloom , I see. I looked at _site_ for the alignment, and this led to the insconsistency.
Thanks for your help.
